# Generated by Django 2.0.5 on 2018-05-06 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternetSpeedTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('download_speed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('upload_speed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('source', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('internet_connection_type', models.SmallIntegerField(choices=[(0, 'ADSL'), (1, 'Satellite'), (2, '3G'), (3, '4G'), (4, '5G'), (5, 'Air')])),
            ],
        ),
        migrations.CreateModel(
            name='OfficeFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='media')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='offices.Office')),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='features',
            field=models.ManyToManyField(related_name='offices', to='offices.OfficeFeature'),
        ),
        migrations.AddField(
            model_name='office',
            name='internet_speed_tests',
            field=models.ManyToManyField(related_name='offices', to='offices.InternetSpeedTest'),
        ),
    ]
